### ISSUE TITLE
Proposal: Reset mechanism for `demand`

### ISSUE THREAD

**Issue by stefan-k** [MatterMiners/cobald#104]
# Proposal

As you may know, our usecase at ATLAS-BFG is a bit unusual. Namely, the queue on the OBS regularly runs empty, which in turn means that we commonly have empty drones running until the end of their lifetime which is obviously inefficient. We would like to implement a mechanism which stops all (empty) drones when there are no jobs in the queue. We are aware that it is against the principle of COBalD/TARDIS to make decisions based on the number of jobs in a queue; however, we think that our proposal will have minimal to no impact on regular use of COBalD/TARDIS, yet is general enough to aid our and potentially other usecases as well. 

In principle, we would like to monitor the number of jobs in pending or running state in the OBS queue. Only if this number is non-zero, `demand` can be larger than `0`, otherwise it will be set to `0`.

# Pseudocode 

Here is some pseudocode based on `LinearController` which illustrates the idea:

```python
@service(flavour=trio)
class LinearController(Controller):
    def __init__(
        self, target: Pool, low_utilisation=0.5, high_allocation=0.5, rate=1, interval=1, reset_handler=None
    ):
        super().__init__(target=target)
        assert rate > 0
        self.rate = rate
        self.interval = interval
        assert low_utilisation <= high_allocation
        self.low_utilisation = low_utilisation
        self.high_allocation = high_allocation
        # "Reset handler" (name open for debate) ideally runs asynchronously in the back.
        self.reset_handler = reset_handler
        if self.reset_handler:
            self.reset_handler.run()

    async def run(self):
        while True:
            self.regulate(self.interval)
            await trio.sleep(self.interval)

    def regulate(self, interval):
        if self.reset_handler and self.reset_handler.reset():
            self.target.demand = 0
        else:
            if self.target.utilisation < self.low_utilisation:
                self.target.demand -= interval * self.rate
            elif self.target.allocation > self.high_allocation:
                self.target.demand += interval * self.rate
```

The reset handlers are based on an interface, such that different usecases can be addressed. They run asynchronously in the background and regularly check whether the conditions for resetting `demand` are met.
In our case the reset handler would obtain the number of jobs in pending or running state in the Slurm queue. `reset_handler.reset()` will return `True` if the number is `0` and `False` otherwise. Obviously the Slurm queue state will only be obtained once every X minutes and cached (much like the adapters in TARDIS work) to avoid putting too much stress on the batch system. 
This change has no effect on the operation of COBalD when no `reset_handler` is configured.

# Other potential use cases 

* "Brute force backfilling": Under certain conditions, such as utilization of the site exceeding a threshold, `demand` could be set to 0 to avoid hogging the resource
* On/Off switch: Manually "pause" COBalD without turning it off. This way running drones are still managed, but no new ones will be acquired. 

# Conclusion 

We believe that this concept has uses beyond our needs and hence is a valuable addition to COBalD. 
We would really appreciate your input on this proposal. The idea was sketched with limited knowledge about COBalD internals, therefore any pointers towards more efficient or practical ways of achieving the goal are highly welcome. 
If your review of this proposal is positive, we are of course willing to provide a PR.

**Comment by stefan-k** [comment]
Our VMs actually power themselves down after they have been idle for a certain time. However, as soon as COBalD/TARDIS notices that no VMs are running, it will immediately start new ones which will again be idle if no jobs were submitted to the OBS in the meantime. With this proposal we would be able to stop COBalD/TARDIS from requesting more drones until jobs are submitted to the OBS. 
Apologies that my initial post didn't make this clear.

**Comment by giffels** [comment]
Okay, sorry. I simply misinterpreted "lifetime" in your posting.

**Comment by maxfischer2781** [comment]
Starting with some technical points. Will drop some thoughts on the use-case after pondering it a bit.

------------

On a technical level, you can always insert a ``Decorator`` between the ``Controller`` and ``Pool``. That allows you to intercept and modify everything going on between the two. In your case a custom ``Decorator`` would usually forward everything verbatim, but if it detects the queue is empty it can pull the plug and force ``demand = 0``.  
Instead of welding the ``reset_handler`` into a specific ``Controller``, this allows you to a) use it with any ``Controller`` and b) package and maintain it separately.

As an example, you can take a look at [the standardiser decorator](https://github.com/MatterMiners/cobald/blob/master/src/cobald/decorator/standardiser.py) which modifies the ``demand`` in both directions.

The point of b) is not to keep this out of the C/T stack, by the way. COBalD isn't the right location for HEP-specific parts, and I'm not sure whether TARDIS would fit this specific piece, but there is no problem for us to create a separate project for such plugins ([the way that indico does](https://github.com/indico/indico-plugins), for example). Conversely, I don't want to force it into the C/T stack either if you prefer code ownership.  
We can provide support in both cases.

**Comment by maxfischer2781** [comment]
As for the use-case, I think this approach will fix your problem but it's most likely not ideal.

My hunch is that the actual issue is that the ``LinearController`` really is not, erm, clever enough. First, it only has a fixed reaction speed so it cannot properly adjust to jobs going away quickly. Second, it will try to crank up the ``demand`` to infinity while things go well so it has to clear a lot of "empty" demand backlog when scaling down. Both of these mean that it reacts very poorly to global task queues running empty.

You might want to give the ``RelativeSupplyController`` a try. It takes the actual supply into account, so it should especially also see your VMs powering down and adjust its demand down.  
There is at least one rough edge about it, in that it might get numerically stuck for low demand – set a lower limit of 10 to be sure.

You can alternatively set the ``surplus`` of the ``Standardiser`` decorator; it limits how much higher the demand is allowed to be than the supply.
```
pipeline:
  # Whatever controller you currently use
  - !LinearController
    low_utilisation: 0.90
    high_allocation: 0.90
    rate: 1
  # Limits the demand for a resource
  - !Standardiser
    minimum: 1
    surplus: 32  # however many resources you are fine to have idle at most
```

If that turns out to be the problem, then puring our effort into a better control strategy might be more productive.

------

Still, as someone working for a VO that also regularly runs out of tasks I certainly do see the benefit in having an emergency stop. What C/T is trying to avoid is *predicting* what the queue content does, but simply checking some minimal fill level isn't bad in itself. Especially if we isolate it in some ``Decorator`` that can be plugged in/out I see now harm in it.

**Comment by stefan-k** [comment]
Thank you for the extensive and useful reply! 

Thanks for pointing me to the possibility of using a decorator, this sounds like a much better way to achieve this compared to  changing the controllers. I agree that this would probably be too specific and wouldn't fit into either COBalD nor TARDIS. Therefore packaging it separately is probably the way to go. Whether we prefer releasing it here or ourselves we'll have to discuss internally.

We did see that `LinearController` isn't the fastest (and we are certainly also wasting resources because of that), but a huge problem for us are the "last one standing" VMs which often run idle for many many hours. Running multiple COBalD/TARDIS instances makes matters even worse. 
I think we chose `LinearController` at some point because of problems with `RelativeSupplyController`, probably the one you mentioned (Its too long ago for me to remember the details). I will certainly give `RelativeSupplyController` another try now.

When using the decorator approach in a separate package, are we able to use the async runners of COBalD?

**Comment by giffels** [comment]
> Therefore packaging it separately is probably the way to go. Whether we prefer releasing it here or ourselves we'll have to discuss internally.

If you do not mind, I would suggest to make it most generic as possible and publish it here, since it might be useful to others as well.

**Comment by stefan-k** [comment]
Implemented in https://github.com/MatterMiners/cobald-hep-plugins/pull/1
