### ISSUE TITLE
Absolute utilisation/allocation

### ISSUE THREAD

**Issue by maxfischer2781** [MatterMiners/cobald#18]
Both `Pool.utilisation` and `Pool.allocation` are commonly undefined at `Pool.supply == 0`. Their definition is usually along the lines of `utilised/supply`, where `utilised` is the absolute utilisation. We currently have two pull requests to handle undefined values via a default (#16) or an exception (#17).

Alternatively, we could change the `Pool` interface to use absolute values, which are always defined. The base case would then be `Pool.supply == Pool.utilised == Pool.allocated == 0`. This obviously avoids the current problem of undefined values. The key question is whether we get *other* undesirable artefacts from this representation.

Please comment here or IRL: @eileen-kuehn @giffels @mschnepf

**Comment by eileen-kuehn** [comment]
For documentation, I think if `Pool.supply == 0` we do have a `Pool.utilisation == Pool.allocation == 1`.
Reasoning: all of the available supply is used and therefore we would have 100% allocation and utilisation. This would mean, that there are not sufficient resources and therefore new would be started letting the values `Pool.utilisation == Pool.allocation == 0` and `Pool.supply > 0`. 
This looks like expected behaviour, doesn't it? Further it ensures that algorithmically we don't have to handle any special cases.

**Comment by maxfischer2781** [comment]
Both #16 and #17 are closed/retracted. I am closing this issue as it seems not to be needed/significant and we did not really find a satisfying alternative to the current situation.
