### ISSUE TITLE
surplus and backlog documentation in LinearController seems flipped

### ISSUE THREAD

**Issue by olifre** [MatterMiners/cobald#69]
Reading through: 

https://github.com/MatterMiners/cobald/blob/4249631370677176b6f7e46010f75dd3e6ddfbae/src/cobald/decorator/standardiser.py#L15-L16

I would expect that `backlog=x` limits the `demand` to be `x` above the `supply`. 
However, the code actually shows that `surplus` seems to do this:
https://github.com/MatterMiners/cobald/blob/4249631370677176b6f7e46010f75dd3e6ddfbae/src/cobald/decorator/standardiser.py#L34

Are `surplus` and `backlog` flipped in the documentation / implementation?

**Comment by maxfischer2781** [comment]
The code currently implements
```python3
supply - backlog < demand < supply + surplus
```
which is at least what was intended by the docstring as well.

I agree that the docstring is somewhat difficult to understand – partially because the wording for ``surplus`` and ``backlog`` is necessarily similar.

Do you think adding the pseudo-formula would help clear up the confusion?

**Comment by olifre** [comment]
> Do you think adding the pseudo-formula would help clear up the confusion?

Ahhh! Yes, indeed, after seeing this formula, I can understand the meaning of the docstrings. 
So I think if this pseudo-formula is added, it would be straightforward to understand :-).
