### ISSUE TITLE
Consumption of 0 interpreted as 1.0

### ISSUE THREAD

**Issue by stefan-k** [MatterMiners/cobald#75]
If consumption is 0, it seems as if it is interpreted as 1:

```
nemo_tardis_c4m22: 2020-03-05 08:27:07 demand = 1000.0 [demand=1000.0, supply=1044.0, utilisation=0.00, consumption=0.00]
changes: 2020-03-05 08:27:08 demand = 1000.0 [demand=1000.0, supply=1044.0, utilisation=1.00, consumption=1.00]
```

This leads to increasing demand, while actually the opposite is true ;)
Once consumption increases to something just slightly above 0, it works again.

I tried to find the part of the code where this happens but I was not successful. 

I think this is a COBalD issue and not a TARDIS issue, but I'm happy to move the issue in case I was wrong.

(Side note: We're also having problems with supply not decreasing/increasing properly as you can see in the log snippet, but this is unrelated and we need to investigate this on our side)

**Comment by maxfischer2781** [comment]
Are you using TARDIS v0.3.0? It [added weighting by ``utilisation``](https://github.com/MatterMiners/tardis/commit/0d657d4bfc81c5719a1302d384b511ff0aa77b6a) (from the previous ``supply``). Due to the way weights work, values automatically fall back to 1.0 if the total is 0. You can see this in the ``utilisation`` being clamped to 1.0 as well.

**Comment by maxfischer2781** [comment]
Any opinion on this, @giffels, @eileen-kuehn?

My hunch is that for ``supply``/``demand`` weights, we want to fall back to ``1.0`` and for ``utilisation``/``allocation`` weights, we want to fall back to ``0.0``. Though taking into account the thoughts on #18, we might want to go for ``supply == 0 -> 1.0`` unconditionally, otherwise compute with a fall back to ``0.0``.

**Comment by stefan-k** [comment]
Yes, I'm using the most recent commit. This explains why I didn't notice this behavior previously.

Is there a way to bypass the weighting for now?

**Comment by maxfischer2781** [comment]
@giffels have you been able to ponder this yet? I remember you mentioning there was some pitfall.

**Comment by mschnepf** [comment]
I think the current solution with `supply == 0 -> 1.0` `allocation` is a good default. It prevents the system from stuck into one status, especially when COBalD starts.

However, more flexibility would be excellent.  I think the simplest solution would be to use the step controller (https://github.com/MatterMiners/cobald/pull/20). The step controller enables to use of different `supply`-ranges different controllers. I'm not sure if yml-configs support the step controller.
Another option would be to through an exception when the `supply` is 0.

This exception should than be handled by an extra controller or something similar, which is 
configurable. This would cause more work.

**Comment by stefan-k** [comment]
I may be misunderstanding something, but I think we are now talking about different things. 

I agree that `supply = 0` should lead to `allocation = 1`. But the problem we are facing is that `utilisation = 0` is interpreted as `utilisation = 1` and `allocation = 0` is interpreted as `allocation = 1`. So in case no jobs are running on the drones, COBalD/TARDIS thinks they are fully utilised and starts even more drones for zero jobs.

Sorry if I'm reiterating something which is absolutely clear to you, I just wanted to make sure we're on the same page :)

**Comment by maxfischer2781** [comment]
No worries, I think we are on the same page here.

The current rule is that *any* ``weight == 0`` bumps ``allocation`` and ``utilisation`` to 1. So if the weight is ``utilisation``, and since ``utilisation <= allocation``, then both ``utilisation`` and ``allocation`` of 0 bump each other up to 1.

My suggestion is to disregard the weight and only look for ``supply == 0``, since that is the *only* point when ``allocation`` and ``utilisation`` are undefined.

@giffels Any final objections?

@mschnepf Supporting the Step Controller via YAML requires some work, but you are right that it would be very useful. Do you want to open a ticket on this?

**Comment by giffels** [comment]
Did I get it right? The problem mentioned by @stefan-k above is caused by https://github.com/MatterMiners/cobald/blob/7f3c391f41ae346705478423ff44086ecf942763/src/cobald/composite/weighted.py#L57-L58 being zero, since the utlisation for all children is zero. Therefore, https://github.com/MatterMiners/cobald/blob/7f3c391f41ae346705478423ff44086ecf942763/src/cobald/composite/weighted.py#L30-L41 is evaluated to one. Which is clearly wrong. 

@maxfischer2781 Just to be on the same page. You would like to change the code to end up with

- `supply==0` => utilsation and allocation -> 1.0
- otherwise => utilsation -> 0.0 and allocation -> 1.0
?

**Comment by maxfischer2781** [comment]
Yep, that's the gist of it.

**Comment by giffels** [comment]
@maxfischer2781 Than, no objections at all.

**Comment by mschnepf** [comment]
Ah, okay. Then sorry for the confusion. It sounds reasonable to me.
@maxfischer2781 Yes, I'll open an issue for the YAML-Support for the step controller.

**Comment by maxfischer2781** [comment]
Changes of #77 have been release in v0.12.1. @stefan-k can you check whether this fixes your problem?

**Comment by stefan-k** [comment]
@maxfischer2781 This fixes our problem, thanks a lot!
